apiVersion: v1
kind: Config
users:
- name: svcs-acct-dply
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjdodVltTW5mYnBRRnJGQ0FXUVJCNmVhcG5tU2J4LXBGZWpPeWpyMEgc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2U0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImplbmtpbnMtdG9rZW4tc3JmcmIiLCJrdWlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiamVua2lucyIsImt1YmVybmV0ZXMuaW8vc2VydmljZ2VydmljZS1hY2NvdW50LnVpZCI6IjBkNjJmMGM4LWNkMTUtNGZkYS1hMTA4LTgzYzY0OGI2NGY3MyIsInN1YiI6InN5c3RlYWNjb3VudDpkZWZhdWx0OmplbmtpbnMifQ.HdILx-yHkoYBMImg0nhLzUNDBKJo21PxDQ_TN1N-rP2RfB44JrF90ONh3IlHt_d-DYnSlRDL95qTsF6xDlTjDm_4g6I6r1G3lMZCk0yRIQ9RWkOfg3LX2KDvcO4tiKa4pjwRrYIirireE5iw2wlcjtMuHF_wd71NeGsj4ERecxawUYc4JOoDDXenBJFwn_GGtPTsC1rRVIyB2xu_cDlqDosszn1KzXSEcpc_OQseCKnllthSrhuRo0wse1HtZnd6nm84SSdOvvdTcso6rEjWwuycGTRqFfTM6KDH7JXE8kFR-TixuA
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0loa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTXpJME1ETXpOREF3SGhjTk1qRXdPVEdXaGNOTXpFd09USXhNVE15TWpJdwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTXpJME1ETXpOR3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTTUdhUkNQb2RaWUYyenZyMHF2NE9HOXZNTHVaTTFCZGVTdERILzEwdjkKMmt0eUhXSjlESGtaSVBQMXdKWmRMMjNubnZwdnU1ZXlxRDRvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBBd0VCL3pBZEJnTlZIUTRFRmdRVW0vRDd1SDNDWnJMNmd2RzM2UHBDCjlUZ2x4UUl3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0ZvQituWTVWa01sMFRaZGF1bGdzeVVORXEKT1d5OW8zQjRCZW5wQWlFQXBDL2ZOUXNGTjBTbnVFYWE5YXFMdlhCcEdrY1ZZc0U1SzQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://127.0.0.1:6443
  name: self-hosted-cluster
contexts:
- context:
    cluster: self-hosted-cluster
    user: svcs-acct-dply
  name: svcs-acct-context
current-context: svcs-acct-context